# Use root/password as user/password credentials (in .env file)

version: '3.1'

services:
  # Database
  mongoDB:
    image: mongo
    container_name: mongodb_chatbot
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
